# Generated by Django 3.0.6 on 2020-05-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongDoanVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaCDV', models.CharField(max_length=5)),
                ('HoTen', models.CharField(max_length=100)),
                ('NgaySinh', models.DateField()),
                ('NgayVaoNganh', models.DateField()),
                ('MatKhau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDonVi', models.CharField(max_length=5)),
                ('TenDonVi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaTour', models.CharField(max_length=5)),
                ('DiaDiem', models.CharField(max_length=1000)),
                ('NgayDi', models.DateField()),
                ('NgayVe', models.DateField()),
                ('ChiTiet', models.TextField(null=True)),
                ('CongDoanVien', models.ManyToManyField(to='QuanLi.CongDoanVien')),
            ],
        ),
        migrations.AddField(
            model_name='congdoanvien',
            name='DonVi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLi.DonVi'),
        ),
    ]
