# Generated by Django 3.0.6 on 2020-05-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='CongDoanVien',
        ),
        migrations.CreateModel(
            name='DKTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CongDoanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLi.CongDoanVien')),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLi.Tour')),
            ],
        ),
    ]
