# Generated by Django 3.0.6 on 2020-05-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLi', '0002_auto_20200517_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('MaCDV', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QuanLi.CongDoanVien')),
                ('MatKhau', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='congdoanvien',
            name='MatKhau',
        ),
    ]
