# Generated by Django 3.0.6 on 2020-06-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLi', '0003_auto_20200519_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='donvi',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
