# Generated by Django 3.0.6 on 2020-06-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLi', '0005_auto_20200603_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donvi',
            old_name='TrangThai',
            new_name='status',
        ),
    ]
