# Generated by Django 3.0.6 on 2020-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLi', '0006_auto_20200603_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donvi',
            name='status',
            field=models.BooleanField(choices=[('false', '0'), ('true', '1')], null=True),
        ),
    ]
