# Generated by Django 3.0.6 on 2020-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLi', '0007_auto_20200603_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congdoanvien',
            name='HoTen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='congdoanvien',
            name='MaCDV',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='donvi',
            name='MaDonVi',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='donvi',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='MaTour',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
